### ISSUE TITLE
How close is this port to completion?

### ISSUE THREAD

**Issue by quicksketch** [backdrop-contrib/redirect#1]
Hi @serundeputy! Thanks for the work on porting this module! We're moving along pretty well on the new BackdropCMS.org site, but of all modules we need for the port, this is the last remaining crucial one.

From a brief look at the code, it looks like it's been converted to use config and all "drupal" functions have been renamed, so it seems to be pretty far along. Do you think it's stable enough for a fairly error-tolerant site to use?

**Comment by quicksketch** [comment]
Oh I meant to include the issue. The progress on the new site is being tracked at https://github.com/backdrop-ops/backdropcms.org/issues/38.

**Comment by serundeputy** [comment]
@quicksketch it is stable enough to use.
You can add redirects on the nodes and through `/admin/config/search/redirect`

~Geoff

**Comment by quicksketch** [comment]
Awesome, that's great to hear! It'd be great to get this into the contrib repo, we don't want another person to start porting it again. The README.md just need a little work to [match the convention](https://github.com/backdrop-ops/contrib/blob/master/README.md) of other modules.

In the mean time I'll give this a spin and I'll post if I find anything. Thanks!

**Comment by serundeputy** [comment]
@quicksketch I had some dpms still in there;  let me take them out.

~~also; I don't know how to get it into the contrib repo; I think I have to apply or something.~~
I applied here:
https://github.com/backdrop-ops/contrib/issues/60

**Comment by serundeputy** [comment]
closing out; feel free to reopen if necessary.
