### ISSUE TITLE
Changing an alias causes a Fatal error on 1.2.0

### ISSUE THREAD

**Issue by quicksketch** [backdrop-contrib/redirect#16]
This was originally filed against core in https://github.com/backdrop/backdrop-issues/issues/1203.

```
Recoverable fatal error: Argument 1 passed to filter_entity_insert() must implement interface EntityInterface, instance of stdClass given in filter_entity_insert() (line 1506 of /backdrop/core/modules/filter/filter.module).
```

Steps to reproduce:
1) create a node (with no alias)
2) set up automatic aliasing for that node type
3) edit the node, check the box for an automatic alias, save
4) edit the node again, uncheck the box for an automatic alias, change the alias, save
5) error.

**Comment by quicksketch** [comment]
The source of this problem is the call to `redirect_save()` takes a stdClass object:

```
    $redirect = new stdClass();
    redirect_object_prepare($redirect);
    $redirect->source = $path['original']['alias'];
    $redirect->redirect = $path['source'];
    $redirect->language = $path['original']['langcode'];
    // Check if the redirect exists before saving.
    $hash = redirect_hash($redirect);
    if (!redirect_load_by_hash($hash)) {
      redirect_save($redirect);
    }
```

But then later it calls all these hook, allowing the redirect to be modified:

```
    // Allow other modules to alter the redirect before saving.
    module_invoke_all('redirect_presave', $redirect);
    module_invoke_all('entity_presave', $redirect, 'redirect');

    // Save the redirect to the database and invoke the post-save hooks.
    if ($redirect->is_new) {
      backdrop_write_record('redirect', $redirect);
      module_invoke_all('redirect_insert', $redirect);
      module_invoke_all('entity_insert', $redirect, 'redirect');
    }
    else {
      backdrop_write_record('redirect', $redirect, array('rid'));
      module_invoke_all('redirect_update', $redirect);
      module_invoke_all('entity_update', $redirect, 'redirect');
    }
```

But when calling `hook_entity_update()`, redirect is passing in a stdClass object instead of a an Entity class. Since redirects aren't entities, I think it would be reasonable to remove these calls to hook_entity_update/insert/presave().

**Comment by quicksketch** [comment]
>  Since redirects aren't entities, I think it would be reasonable to remove these calls to hook_entity_update/insert/presave(). 

Well I'm incorrect here. Redirects _are_ entities, but they're not fully ported to Backdrop.

**Comment by quicksketch** [comment]
Filed https://github.com/backdrop-contrib/redirect/issues/17 to fully convert redirects to real objects instead of `stdClass` objects.

Overall, I'm not certain why redirects need to be entities at all. But alas, it's what they are currently so finishing the integration seems to make more sense than trying to de-entitify it.

**Comment by serundeputy** [comment]
I followed these instructions, but it did not produce an error.

> Steps to reproduce:
> 1) create a node (with no alias)
> 2) set up automatic aliasing for that node type
> 3) edit the node, check the box for an automatic alias, save
> 4) edit the node again, uncheck the box for an automatic alias, change the alias, save
> 5) error.

I'll update core to 1.2.0 and see if I can replicate (currently I'm on 1.1.3)

**Comment by quicksketch** [comment]
> I'll update core to 1.2.0 and see if I can replicate

Yeah, this only happens if you have 1.2.0. You can also reproduce it just by editing any existing redirect I believe.

**Comment by serundeputy** [comment]
I replicated on `1.x` which of course includes `1.2.0` I'm pulling down the patch now.

**Comment by quicksketch** [comment]
Thanks @serundeputy!
