### ISSUE TITLE
404 pages not offering link to create redirect

### ISSUE THREAD

**Issue by serundeputy** [backdrop-contrib/redirect#2]
this on line 1406 of the redirect module:

``` php
/**
 * Returns if the current page request is a page not found (404 status error).
 *
 * Why the fuck do we have to do this? Why is there not an easier way???
 *
 * @return
 *   TRUE if the current page is a 404, or FALSE otherwise.
 * todo: BACKDROP_PORT get the 404 tests working.
 */
function redirect_is_current_page_404() {
  //dpm('::'.backdrop_get_http_header('Status').'::');
  return backdrop_get_http_header('Status') == '404 Not Found';
}
```

this is causing simpletets to fail.

**Comment by quicksketch** [comment]
Filed a PR at https://github.com/backdrop-contrib/redirect/pull/7. When we added Layouts, we significantly de-ghetto-ified 404 page handling. Although we could have done something similar to the old approach using hook_layout_preprocess(), I think just making a menu entry normally is a much easier and cleaner solution.

**Comment by serundeputy** [comment]
thanks; that one was really pestering me!
way to go @quicksketch

**Comment by quicksketch** [comment]
Thanks @serundeputy! Great job porting this module. It works!
