### ISSUE TITLE
Receive "Cannot determine the type of project" error on a fresh install of Bd 1.2.2 

### ISSUE THREAD

**Issue by sutibun** [backdrop-contrib/redirect#20]
When I copy the download link from the Bd project page and paste into my Bd site, I get the following error:

![installtype](https://cloud.githubusercontent.com/assets/14132746/10270902/c849fc48-6ac5-11e5-92f5-3a2e95364be4.png)

Meaning, I can't install it via the GUI.

Hesitated to bring this up since this issue is similar to the one I [encountered with the Honeypot module](https://github.com/backdrop-contrib/honeypot/issues/6) but just to bring awareness since I like this module.

PS: Installation works if you do it by uploading module via FTP.

**Comment by serundeputy** [comment]
Hi @sutibun thanks for reporting this.

I took a look at the corresponding honeypot issue and as you may know looks like there is not a known solution for this problem yet.  So for the short term looks like FTP is the way to go.

If they solve it over in honeypot feel free to ping back over here so we can implement it in redirect.

thanks,
~Geoff

**Comment by sutibun** [comment]
@serundeputy No problemo.

Maybe add a note on project page that FTP is the way to go?

**Comment by jenlampton** [comment]
@serundeputy The solution is to add a `type = module` to the very top of all info files (including ones in tests). It's true that this shouldn't be necessary after https://github.com/backdrop/backdrop-issues/issues/1294 is completed, but that would enable people to use the project now.

**Comment by serundeputy** [comment]
@sutibun @jenlampton I've added the line `type = module` to the `redirect.tests.info` file in `1.x-1x`.

I don't have any servers that allow ftp set up.  So, if one of you would be kind enough to test this out  .... if all is well I can make another release :)

https://github.com/backdrop-contrib/redirect/archive/1.x-1.x.zip

thanks,
~Geoff

**Comment by jenlampton** [comment]
@serundeputy that worked for me, woohoo! :+1:

**Comment by serundeputy** [comment]
Thanks @jenlampton new release https://github.com/backdrop-contrib/redirect/releases/download/1.x-1.0.4/redirect.zip

closing.

**Comment by sutibun** [comment]
Yay, thanks.
