### ISSUE TITLE
PHP error: Array to string conversion in backdrop_send_headers() (line 1509 of core/includes/bootstrap.inc)

### ISSUE THREAD

**Issue by jackaponte** [backdrop-contrib/redirect#22]
I'm using Backdrop 1.3.5 and Redirect 1.x-1.0.4. I created a couple of redirects, one to a view page and one to the site front page. When attempting to access either redirect I got a white screen; the following error was logged to the Backdrop logs:

`Notice: Array to string conversion in backdrop_send_headers() (line 1509 of /var/www/backdrop-site/core/includes/bootstrap.inc).`

**Comment by jackaponte** [comment]
Looks to me like the problem is in `redirect.module`, where `redirect_status_code_options($redirect->status_code)` is being handled as a string instead of an array, which it sometimes is. I'm going to submit a pull request with a proposed fix; it's my first pull request ever so hopefully I'll get it right!

**Comment by jackaponte** [comment]
OK--I [submitted a pull request](https://github.com/backdrop-contrib/redirect/pull/23) but realize I'm probably not fully solving the problem here. I'm just checking to see if `redirect_status_code_options($redirect->status_code)` is NULL, then passing it through if so, but what about if it is _not_ NULL? I'm not accounting for that yet.

**Comment by serundeputy** [comment]
Hi @jackaponte sorry just seeing this now.

Now that `redirect` is in core is this still an issue?

sorry for the delay 😟 

~Geoff

**Comment by jackaponte** [comment]
No worries about the delay, Geoff! I haven't gotten to test and see if the bug is still there now that `redirect` is in core,  but I'll try to do so soon.

**Comment by jackaponte** [comment]
> Now that redirect is in core is this still an issue?

This is LONG overdue, but no, this no longer seems to be an issue! Thanks Geoff. :)
