### ISSUE TITLE
Remove all existing update hooks, provide upgrade path?

### ISSUE THREAD

**Issue by quicksketch** [backdrop-contrib/redirect#3]
Does this module need an upgrade path from D7?

Upon trying to upgrade from D7, the updates for 1 - 6 are requested to be run again. However, I think these updates are from the D5 era. They should all be removed.

Lastly, providing a `hook_update_last_removed()` would be a good addition, with "7000" being the last update. There is also a 7100 update, but it does nothing.

**Comment by serundeputy** [comment]
haha; i was working on this reques, but your PR came in while I was working.

thanks for the great work @quicksketch :+1:
